alias dp="docker ps"        
alias dpa="docker ps -a"   
alias di="docker images"  
alias dip="docker inspect --format '{{ .NetworkSettings.IPAddress }}'" 
alias dr="docker run"
alias drm="docker rm"
alias drmi="docker rmi"
alias de="docker exec"
alias dco="docker-compose"
dalias() { alias | grep 'docker' | sed "s/^\([^=]*\)=\(.*\)/\1 => \2/"| sed "s/['|\']//g" | sort; }
